### ISSUE TITLE
Assess how to merge this project into `witnet-radon-js` as `witnet-js`

### ISSUE THREAD

**Issue by aesedepece** [witnet/witnet-requests-js#39]

**Comment by Tommytrg** [comment]
Currently, we are using two different libraries to handle RADON: `witnet-radon-js` and `witnet-requests-js`. Initially, each library has its specific purpose, but we have repeated features over time, and we could unify the libraries to simplify the development process by maintaining one source code.

### witnet-requests-js

This javascript library helps compose data requests, encode them in CBOR, and generates a solidity contract using the crafted data request. It also includes a witnet-toolkit which allows running data requests locally.
- Smart contract oriented library but includes more features than witnet-radon-js.
- Support data request arguments such as fees
- Uses a proxy to transform Script.methodName -> Script.apply(methodName)
- Includes witnet-toolkit

This library exports the following classes: Request, Source, Script, Aggregator and Tally.
	  
#### Request

- constructor ()
- addSource (source)
- setAggregator (aggregator)
- setTally (tally)
- setQuorum (witnesses, min_consensus_percentage)
- setCollateral (collateral)
- setFees (reward, commit_and_reveal_fee)
- schedule (timestamp)
- setTimestamp (timestamp)
- asJson ()

#### Source

- constructor (url) // extends Script

#### Script

- constructor (firstType)
- apply (operator)
- encode ()

#### Aggregator

- constructor ({ filters = [], reducer })
- pack ()
-  
#### Tally

- constructor ({ filters = [], reducer })
- pack ()

### witnet-radon-js

This typescript library helps compose data requests and generate a Markup representation of Radon from Radon Mir to help build data requests using a UI. The library allows compiling RADON MARKUP into RADON MIR and backward. Moreover, it can generate `witnet-requests-js` code.

- UI oriented library
- Doesn't support data request arguments such as fees
- Too long tests, it's extremely difficult maintain them and are too decoupled to the hole code.

Exports the following classes: Radon, Source, Script, Operator.

#### Radon
- constructor(radRequest: MirRequest, locale?: Locale)
- setLocale(locale: Locale)
- addOperator(scriptId: number)
- addSource()
- deleteOperator(scriptId: number, operatorId: number)
- deleteSource(sourceIndex: number)
- getJs(): string // [Return request-js code](https://github.com/witnet/witnet-radon-js/blob/master/src/radon.ts#L54)
- getMarkup(): MarkupRequest
- getMir(): MirRequest
- update(id: number, value: any)
- updateSource(sourceIndex: number, args: any)

#### Source
- constructor(context: { cache: Cache; i18n: I18n }, source: MirSource)
- public getJs(index: number): string
-  public getMir(): MirSource
- getMarkup(): MarkupSource
- getOutputType(): OutputType
- update(args: { kind: string; url: string; contentType: string })
	
#### Script
- constructor(context: Context, script: MirScript, firstType: OutputType=DEFAULT_SCRIPT_FIRST_TYPE )
- addOperator()
- deleteOperator(operatorId: number)
- findIdx(operatorId: number)
- getJs(): string
- getJs(): string
- getLastOperator(): Operator | null
- getMarkup(): MarkupScript
- getMir(): MirScript
- getOutputType(): OutputType
- onChildrenEvent()
- push(operator: MirOperator)
- validateScript(index?: number)
	  
#### Operator
- constructor(context: Context, scriptId: number, inputType: OutputType | null, operator: MirOperator | null, eventEmitter: EventEmitter ) 
- getJs(): string
- getMarkup(): MarkupOperator
- getMir(): MirOperator
- update(value: keyof typeof OperatorCode | OperatorCode)

| radon-js    | request-js  |
| ----------- | ----------- |
| Radon       | Request     |
| Source      | Source      |
| Script      | Aggregator  |
| Script      | Tally       |
| Operator    | -           |


### Decisions to make:

- Decide if we want to create a new library unifying `witnet-radon-js` and `witnet-requests-js` or add the missing features in one of them.
- My personal preference is to use typescript to make a more robust library so, we should type `witnet-requests-js` code.
- Look for a way to improve testing in `witnet-radon-js`. IMO, this is out of the scope of this PR.
- The resulting library should contain the features of both libraries that don't overlap.
- To merge the RADON business logic, we should decide if we support both ways to use the library or prefer one over the other. I think we could maintain both styles adding a proxy to `witnet-radon-js` logic in the same way `witnet-requests-js` implements it to be able to add methods as `.methodName`.


#### witnet-requests-js
```js
const bitstamp = new Witnet.Source("https://www.bitstamp.net/api/v2/ticker/ethusd/")
  .parseJSONMap() // Parse a `Map` from the retrieved `String`
```

#### witnet-radon-js

```js 
const script = new Script(context, mirScript)
script.push(OperatorCode.BooleanAsString)
```

**Comment by aesedepece** [comment]
I can call this done. Next sprint, let's discuss!
