### ISSUE TITLE
npx rad2sol keeps giving me 404 error.

### ISSUE THREAD

**Issue by justanotherdev89** [witnet/witnet-requests-js#74]
I tried following the get request tutorial, but it keeps giving me the 404 error.

Tried many ways to solve the issue but no luck. 
Following is the error I get. It seems like it's not reading rad2sol from the node_modules installed.
It's not also located in .bin folder. What would be the best way to resolve this issue?

```npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/rad2sol - Not found
npm ERR! 404
npm ERR! 404  'rad2sol@latest' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.```

**Comment by aesedepece** [comment]
Hi @justanotherdev89! Thanks for reporting.

This may be fixed in #72. We'll be getting that merged and released ASAP. Then I'll appreciate a lot your confirmation of the fix.

Thanks in advance!

**Comment by justanotherdev89** [comment]
Sure, np! Thanks for the quick works!

**Comment by aesedepece** [comment]
I think this is fixed, right?

**Comment by justanotherdev89** [comment]
Yeap it is fixed!
