### ISSUE TITLE
Upgrade to witnet-toolkit v1.6.7

### ISSUE THREAD

**Issue by guidiaz** [witnet/witnet-requests-js#86]
Should fix #84.

**Comment by Tommytrg** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Witnet-Foundation-5c13a9364d778414b5ba555c/issues/witnet/witnet-requests-js/86?planning-poker) with Zenhub @aesedepece @gabaldon @guidiaz @aeweda

**Comment by guidiaz** [comment]
Related PRs:
- https://github.com/witnet/witnet-requests-js/pull/87
- https://github.com/witnet/witnet-solidity/pull/12
